// generated by stringer -type=decodeState; DO NOT EDIT

package goheatshrink

import "fmt"

const _decodeState_name = "decodeStateTagBitdecodeStateYieldLiteraldecodeStateBackRefIndexMSBdecodeStateBackRefIndexLSBdecodeStateBackRefCountMSBdecodeStateBackRefCountLSBdecodeStateYieldBackRef"

var _decodeState_index = [...]uint8{17, 40, 66, 92, 118, 144, 167}

func (i decodeState) String() string {
	if i < 0 || i >= decodeState(len(_decodeState_index)) {
		return fmt.Sprintf("decodeState(%d)", i)
	}
	hi := _decodeState_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _decodeState_index[i-1]
	}
	return _decodeState_name[lo:hi]
}
