// generated by stringer -type=DecodeState; DO NOT EDIT

package goheatshrink

import "fmt"

const _DecodeState_name = "DecodeStateUnknownDecodeStateTagBitDecodeStateYieldLiteralDecodeStateBackRefIndexMSBDecodeStateBackRefIndexLSBDecodeStateBackRefCountMSBDecodeStateBackRefCountLSBDecodeStateYieldBackRef"

var _DecodeState_index = [...]uint8{18, 35, 58, 84, 110, 136, 162, 185}

func (i decodeState) String() string {
	if i < 0 || i >= decodeState(len(_DecodeState_index)) {
		return fmt.Sprintf("DecodeState(%d)", i)
	}
	hi := _DecodeState_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _DecodeState_index[i-1]
	}
	return _DecodeState_name[lo:hi]
}
