// generated by stringer -type=encodeState; DO NOT EDIT

package goheatshrink

import "fmt"

const _encodeState_name = "encodeStateNotFullencodeStateFilledencodeStateSearchencodeStateYieldTagBitencodeStateYieldLiteralencodeStateBackRefIndexencodeStateBackRefLengthencodeStateSaveBacklogencodeStateFlushBitsencodeStateDone"

var _encodeState_index = [...]uint8{18, 35, 52, 74, 97, 120, 144, 166, 186, 201}

func (i encodeState) String() string {
	if i < 0 || i >= encodeState(len(_encodeState_index)) {
		return fmt.Sprintf("encodeState(%d)", i)
	}
	hi := _encodeState_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _encodeState_index[i-1]
	}
	return _encodeState_name[lo:hi]
}
